[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/cloudflare/brotli-go"
    unused-packages = false



[[constraint]]
  name = "github.com/facebookgo/grace"
  revision = "75cf19382434e82df4dd84953f566b8ad23d6e9e"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  revision = "ed7bcb39ff10f39ab08e317ce16df282845852fa"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "=0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "=0.9.0-pre1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=1.4.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.1"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"  # master required by github.com/miekg/dns

[[constraint]]
  name = "golang.org/x/sync"
  revision = "1d60e4601c6fd243af51cc01ddf169918a5407ca"

[[constraint]]
  name = "gopkg.in/urfave/cli.v2"
  source = "https://github.com/cbranch/cli"
  branch = "altsrc-parse-durations"

[[constraint]]
  name = "zombiezen.com/go/capnproto2"
  source = "https://github.com/zombiezen/go-capnproto2"
  version = "=2.17.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/coredns/coredns"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "=1.1.8"

[[constraint]]
  name = "github.com/cloudflare/brotli-go"
  revision = "18c9f6c67e3dfc12e0ddaca748d2887f97a7ac28"

[[override]]
  name = "github.com/mholt/caddy"
  revision = "d3b731e9255b72d4571a5aac125634cf1b6031dc"

[[constraint]]
  name = "github.com/coreos/go-oidc"
  revision = "a93f71fdfe73d2c0f5413c0565eea0af6523a6df"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"  # master required by github.com/miekg/dns

[[constraint]]
  name = "github.com/cloudflare/golibs"
  revision = "333127dbecfcc23a8db7d9a4f52785d23aff44a1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "=1.1.1"

[[constraint]]
  name = "github.com/gliderlabs/ssh"
  revision = "63518b5243e0fe306cc35cb382f459de123e550e"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.23.9"
